Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
end