Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
  config.vm.box_version = "20201203.01"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
end